export const dummyJobs = {
  "random-key-1": {
    id: "random-key-1",
    orgID: "otakuneko23@gmail.com",
    status: "Approved",
    title: "Python teacher",
    beneficiaries: ["Children", "Teens"],
    skills: ["Python", "Teaching"],
    purpose: "Teach students python",
    platform: "Physical",
    multiLocation: false,
    location: "Bukit Panjang Plaza",
    postalCode: 677743,
    type: "Ad hoc",
    flexiDate: false,
    longStartDate: null,
    longEndDate: null,
    flexiHours: false,
    longHours: null,
    adShift: [
      { date: new Date("2021-05-25"), startTime: "17:30", endTime: "19:30" },
      { date: new Date("2021-04-02"), startTime: "17:00", endTime: "19:00" },
    ],
    addInfo: "All teachers will be reimbursed at $20 an hour",
    imageUrl: "https://miro.medium.com/max/1200/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg",
    pocName: "Rayner",
    pocNo: 98365567,
    pocEmail: "raynerljm@gmail.com",
    datePosted: new Date("2020-06-06"),
    applicants: ["app-id-1"],
  },
  "random-key-2": {
    id: "random-key-2",
    orgID: "peepeetime@gmail.com",
    status: "Pending",
    title: "CS2100 Tutor",
    beneficiaries: ["Youths"],
    skills: ["C++"],
    purpose: "Teach students python",
    platform: "Virtual",
    multiLocation: null,
    location: null,
    postalCode: null,
    type: "Long term",
    flexiDate: false,
    longStartDate: new Date("2021-01-06"),
    longEndDate: new Date("2021-12-31"),
    flexiHours: false,
    longHours: 140,
    adShift: null,
    addInfo: "TAs will be paid $40 an hour -HAND",
    imageUrl: "https://www.comp.nus.edu.sg/stfphotos/tantc.jpg",
    pocName: "Zechary",
    pocNo: 91234567,
    pocEmail: "peepeetime@gmail.com",
    datePosted: new Date("2020-05-13"),
    applicants: [],
  },
  "random-key-3": {
    id: "random-key-3",
    orgID: "testflexiDate@gmail.com",
    status: "Rejected",
    title: "FlexiDate Test",
    beneficiaries: ["Elderly"],
    skills: ["Smartphone"],
    purpose: "Teach elderly phone stuff",
    platform: "Physical",
    multiLocation: true,
    location: null,
    postalCode: null,
    type: "Long term",
    flexiDate: true,
    longStartDate: new Date("2021-01-06"),
    longEndDate: new Date("2021-12-31"),
    flexiHours: true,
    longHours: 140,
    adShift: null,
    addInfo: "Teachers will be paid $90 an hour",
    imageUrl: "http://www.mandysam.com/img/random.jpg",
    pocName: "MrKuku",
    pocNo: 88887777,
    pocEmail: "testflexiDate@gmail.com",
    datePosted: new Date("2015-02-10"),
    applicants: [],
  },
};

export const dummyOrgs = {
  "otakuneko23@gmail.com": {
    id: "otakuneko23@gmail.com",
    type: "NUS Organization",
    name: "NUS Hackers",
    uen: null,
    email: "otakuneko23@gmail.com",
    pocName: "Rayner",
    pocNo: 98365567,
    pocEmail: "raynerljm@gmail.com",
    dateCreated: new Date("Dec 28 1998"),
    jobsPosted: ["random-key-1"],
  },
  "peepeetime@gmail.com": {
    id: "peepeetime@gmail.com",
    type: "Non-NUS Organization",
    name: "Zechary's Charities",
    uen: 6969123,
    email: "peepeetime@gmail.com",
    pocName: "Zechary Au",
    pocNo: 92345678,
    pocEmail: "peepeetime@gmail.com",
    dateCreated: new Date("Jul 11 2017"),
    jobsPosted: ["random-key-2"],
  },
  "testflexiDate@gmail.com": {
    id: "testflexiDate@gmail.com",
    type: "Non-NUS Organization",
    name: "St Theresa's Home",
    uen: 888443,
    email: "testflexiDate@gmail.com",
    pocName: "Ng Wan Yu",
    pocNo: 91079192,
    pocEmail: "testflexiDate@gmail.com",
    dateCreated: new Date("February 23 2005"),
    jobsPosted: ["random-key-3"],
  },
};

export const dummyApps = {
  "app-id-1": {
    id: "app-id-1",
    stuID: "1@gmail.com",
    jobID: "random-key-1",
    status: "Pending",
    stuAddInfo: "I am bob and i am smart",
    dateApplied: new Date("2021-05-04"),
  },
};

export const dummyStus = {
  "1@gmail.com": {
    id: "1@gmail.com",
    name: "Bob",
    dob: new Date("1999-10-12"),
    email: "1@gmail.com",
    contactNo: "12345678",
    course: "Computer Science",
    yearOfStudy: "Year 1",
    dateCreated: new Date("2021-06-04"),
    jobsApplied: ["app-id-1"],
  },
};
